"""weights.py
~~~~~~~~~~~~
Definições de pesos por setor e indicadores genéricos (fallback) para scoring.

Variáveis públicas
------------------
- PESOS_POR_SETOR: dict de pesos ajustados por setor
- INDICADORES_SCORE: dict de pesos genéricos (fallback)
"""

# Pesos por setor (setor -> {indicador: {'peso': float, 'melhor_alto': bool}, ...})
PESOS_POR_SETOR = {
    "Financeiro": {
        'ROE_mean': {'peso': 0.28, 'melhor_alto': True},
        'P/VP_mean': {'peso': 0.15, 'melhor_alto': False},
        'DY_mean': {'peso': 0.15, 'melhor_alto': True},
        'Endividamento_Total_mean': {'peso': 0.05, 'melhor_alto': False},
        'Liquidez_Corrente_mean': {'peso': 0.07, 'melhor_alto': True},
        'Margem_Liquida_mean': {'peso': 0.10, 'melhor_alto': True},
        'Lucro_Liquido_slope_log': {'peso': 0.10, 'melhor_alto': True},
        'Momentum_12m': {'peso': 0.10, 'melhor_alto': True},
    },
    "Tecnologia da Informação": {
        'Margem_Liquida_mean': {'peso': 0.07, 'melhor_alto': True},
        'Margem_Operacional_mean': {'peso': 0.09, 'melhor_alto': True},
        'ROE_mean': {'peso': 0.06, 'melhor_alto': True},
        'ROA_mean': {'peso': 0.04, 'melhor_alto': True},
        'ROIC_mean': {'peso': 0.07, 'melhor_alto': True},
        'P/VP_mean': {'peso': 0.03, 'melhor_alto': False},
        'DY_mean': {'peso': 0.02, 'melhor_alto': True},
        'Endividamento_Total_mean': {'peso': 0.03, 'melhor_alto': False},
        'Alavancagem_Financeira_mean': {'peso': 0.03, 'melhor_alto': False},
        'Liquidez_Corrente_mean': {'peso': 0.04, 'melhor_alto': True},
        'Receita_Liquida_slope_log': {'peso': 0.15, 'melhor_alto': True},
        'Lucro_Liquido_slope_log': {'peso': 0.14, 'melhor_alto': True},
        'Patrimonio_Liquido_slope_log': {'peso': 0.05, 'melhor_alto': True},
        'Divida_Liquida_slope_log': {'peso': 0.02, 'melhor_alto': False},
        'Caixa_Liquido_slope_log': {'peso': 0.05, 'melhor_alto': True},
        'Momentum_12m': {'peso': 0.11, 'melhor_alto': True},
    },
    "Energia": {
        'Margem_Liquida_mean': {'peso': 0.07, 'melhor_alto': True},
        'Margem_Operacional_mean': {'peso': 0.09, 'melhor_alto': True},
        'ROE_mean': {'peso': 0.06, 'melhor_alto': True},
        'ROA_mean': {'peso': 0.05, 'melhor_alto': True},
        'ROIC_mean': {'peso': 0.06, 'melhor_alto': True},
        'P/VP_mean': {'peso': 0.03, 'melhor_alto': False},
        'DY_mean': {'peso': 0.16, 'melhor_alto': True},
        'Endividamento_Total_mean': {'peso': 0.08, 'melhor_alto': False},
        'Alavancagem_Financeira_mean': {'peso': 0.05, 'melhor_alto': False},
        'Liquidez_Corrente_mean': {'peso': 0.08, 'melhor_alto': True},
        'Receita_Liquida_slope_log': {'peso': 0.05, 'melhor_alto': True},
        'Lucro_Liquido_slope_log': {'peso': 0.05, 'melhor_alto': True},
        'Patrimonio_Liquido_slope_log': {'peso': 0.02, 'melhor_alto': True},
        'Divida_Liquida_slope_log': {'peso': 0.02, 'melhor_alto': False},
        'Caixa_Liquido_slope_log': {'peso': 0.05, 'melhor_alto': True},
        'Momentum_12m': {'peso': 0.13, 'melhor_alto': True},
    },
    "Industrial": {
        'Margem_Liquida_mean': {'peso': 0.07, 'melhor_alto': True},
        'Margem_Operacional_mean': {'peso': 0.10, 'melhor_alto': True},
        'ROE_mean': {'peso': 0.07, 'melhor_alto': True},
        'ROA_mean': {'peso': 0.05, 'melhor_alto': True},
        'ROIC_mean': {'peso': 0.10, 'melhor_alto': True},
        'P/VP_mean': {'peso': 0.07, 'melhor_alto': False},
        'DY_mean': {'peso': 0.04, 'melhor_alto': True},
        'Endividamento_Total_mean': {'peso': 0.07, 'melhor_alto': False},
        'Alavancagem_Financeira_mean': {'peso': 0.04, 'melhor_alto': False},
        'Liquidez_Corrente_mean': {'peso': 0.04, 'melhor_alto': True},
        'Receita_Liquida_slope_log': {'peso': 0.08, 'melhor_alto': True},
        'Lucro_Liquido_slope_log': {'peso': 0.08, 'melhor_alto': True},
        'Patrimonio_Liquido_slope_log': {'peso': 0.04, 'melhor_alto': True},
        'Divida_Liquida_slope_log': {'peso': 0.04, 'melhor_alto': False},
        'Caixa_Liquido_slope_log': {'peso': 0.04, 'melhor_alto': True},
        'Momentum_12m': {'peso': 0.07, 'melhor_alto': True},
    },
    "Consumo Cíclico": {
        'Margem_Liquida_mean': {'peso': 0.10, 'melhor_alto': True},
        'Margem_Operacional_mean': {'peso': 0.08, 'melhor_alto': True},
        'ROE_mean': {'peso': 0.08, 'melhor_alto': True},
        'ROA_mean': {'peso': 0.05, 'melhor_alto': True},
        'ROIC_mean': {'peso': 0.09, 'melhor_alto': True},
        'P/VP_mean': {'peso': 0.06, 'melhor_alto': False},
        'DY_mean': {'peso': 0.05, 'melhor_alto': True},
        'Endividamento_Total_mean': {'peso': 0.07, 'melhor_alto': False},
        'Alavancagem_Financeira_mean': {'peso': 0.04, 'melhor_alto': False},
        'Liquidez_Corrente_mean': {'peso': 0.04, 'melhor_alto': True},
        'Receita_Liquida_slope_log': {'peso': 0.15, 'melhor_alto': True},
        'Lucro_Liquido_slope_log': {'peso': 0.09, 'melhor_alto': True},
        'Patrimonio_Liquido_slope_log': {'peso': 0.04, 'melhor_alto': True},
        'Divida_Liquida_slope_log': {'peso': 0.04, 'melhor_alto': False},
        'Caixa_Liquido_slope_log': {'peso': 0.04, 'melhor_alto': True},
        'Momentum_12m': {'peso': 0.07, 'melhor_alto': True},
    },
    "Consumo não Cíclico": {
        'Margem_Liquida_mean': {'peso': 0.09, 'melhor_alto': True},
        'Margem_Operacional_mean': {'peso': 0.09, 'melhor_alto': True},
        'ROE_mean': {'peso': 0.08, 'melhor_alto': True},
        'ROA_mean': {'peso': 0.05, 'melhor_alto': True},
        'ROIC_mean': {'peso': 0.07, 'melhor_alto': True},
        'DY_mean': {'peso': 0.14, 'melhor_alto': True},
        'P/VP_mean': {'peso': 0.06, 'melhor_alto': False},
        'Endividamento_Total_mean': {'peso': 0.06, 'melhor_alto': False},
        'Alavancagem_Financeira_mean': {'peso': 0.04, 'melhor_alto': False},
        'Liquidez_Corrente_mean': {'peso': 0.04, 'melhor_alto': True},
        'Receita_Liquida_slope_log': {'peso': 0.07, 'melhor_alto': True},
        'Lucro_Liquido_slope_log': {'peso': 0.07, 'melhor_alto': True},
        'Patrimonio_Liquido_slope_log': {'peso': 0.03, 'melhor_alto': True},
        'Divida_Liquida_slope_log': {'peso': 0.03, 'melhor_alto': False},
        'Caixa_Liquido_slope_log': {'peso': 0.04, 'melhor_alto': True},
        'Momentum_12m': {'peso': 0.10, 'melhor_alto': True},
    },
    "Materiais Básicos": {
        'Margem_Operacional_mean': {'peso': 0.12, 'melhor_alto': True},
        'Margem_Liquida_mean': {'peso': 0.07, 'melhor_alto': True},
        'ROE_mean': {'peso': 0.08, 'melhor_alto': True},
        'ROIC_mean': {'peso': 0.08, 'melhor_alto': True},
        'DY_mean': {'peso': 0.12, 'melhor_alto': True},
        'P/VP_mean': {'peso': 0.06, 'melhor_alto': False},
        'Endividamento_Total_mean': {'peso': 0.07, 'melhor_alto': False},
        'Alavancagem_Financeira_mean': {'peso': 0.05, 'melhor_alto': False},
        'Liquidez_Corrente_mean': {'peso': 0.03, 'melhor_alto': True},
        'Receita_Liquida_slope_log': {'peso': 0.06, 'melhor_alto': True},
        'Lucro_Liquido_slope_log': {'peso': 0.06, 'melhor_alto': True},
        'Patrimonio_Liquido_slope_log': {'peso': 0.03, 'melhor_alto': True},
        'Divida_Liquida_slope_log': {'peso': 0.02, 'melhor_alto': False},
        'Caixa_Liquido_slope_log': {'peso': 0.02, 'melhor_alto': True},
        'Momentum_12m': {'peso': 0.15, 'melhor_alto': True},
    },
    "Petróleo, Gás e Biocombustíveis": {
        'DY_mean': {'peso': 0.30, 'melhor_alto': True},
        'Margem_Operacional_mean': {'peso': 0.25, 'melhor_alto': True},
        'ROIC_mean': {'peso': 0.18, 'melhor_alto': True},
        'Liquidez_Corrente_mean': {'peso': 0.10, 'melhor_alto': True},
        'Endividamento_Total_mean': {'peso': 0.10, 'melhor_alto': False},
        'Momentum_12m': {'peso': 0.10, 'melhor_alto': True},
    },
    "Saúde": {
        'Receita_Liquida_slope_log': {'peso': 0.25, 'melhor_alto': True},
        'Lucro_Liquido_slope_log': {'peso': 0.25, 'melhor_alto': True},
        'Margem_Operacional_mean': {'peso': 0.20, 'melhor_alto': True},
        'ROE_mean': {'peso': 0.15, 'melhor_alto': True},
        'Endividamento_Total_mean': {'peso': 0.07, 'melhor_alto': False},
        'Momentum_12m': {'peso': 0.08, 'melhor_alto': True},
    },
    "Comunicações": {
        'Margem_Liquida_mean': {'peso': 0.07, 'melhor_alto': True},
        'Margem_Operacional_mean': {'peso': 0.15, 'melhor_alto': True},
        'ROE_mean': {'peso': 0.08, 'melhor_alto': True},
        'ROA_mean': {'peso': 0.05, 'melhor_alto': True},
        'ROIC_mean': {'peso': 0.12, 'melhor_alto': True},
        'P/VP_mean': {'peso': 0.05, 'melhor_alto': False},
        'DY_mean': {'peso': 0.12, 'melhor_alto': True},
        'Endividamento_Total_mean': {'peso': 0.06, 'melhor_alto': False},
        'Alavancagem_Financeira_mean': {'peso': 0.04, 'melhor_alto': False},
        'Liquidez_Corrente_mean': {'peso': 0.07, 'melhor_alto': True},
        'Receita_Liquida_slope_log': {'peso': 0.07, 'melhor_alto': True},
        'Lucro_Liquido_slope_log': {'peso': 0.07, 'melhor_alto': True},
        'Momentum_12m': {'peso': 0.08, 'melhor_alto': True},
    },
    "Bens Industriais": {
        'Margem_Operacional_mean': {'peso': 0.22, 'melhor_alto': True},
        'ROIC_mean': {'peso': 0.22, 'melhor_alto': True},
        'Receita_Liquida_slope_log': {'peso': 0.12, 'melhor_alto': True},
        'Liquidez_Corrente_mean': {'peso': 0.11, 'melhor_alto': True},
        'P/VP_mean': {'peso': 0.09, 'melhor_alto': False},
        'Endividamento_Total_mean': {'peso': 0.09, 'melhor_alto': False},
        'Momentum_12m': {'peso': 0.15, 'melhor_alto': True},
    },
    "Utilidade Pública": {
        'Margem_Liquida_mean': {'peso': 0.07/1.15, 'melhor_alto': True},
        'Margem_Operacional_mean': {'peso': 0.10/1.15, 'melhor_alto': True},
        'ROE_mean': {'peso': 0.05/1.15, 'melhor_alto': True},
        'ROA_mean': {'peso': 0.03/1.15, 'melhor_alto': True},
        'ROIC_mean': {'peso': 0.05/1.15, 'melhor_alto': True},
        'P/VP_mean': {'peso': 0.05/1.15, 'melhor_alto': False},
        'DY_mean': {'peso': 0.20/1.15, 'melhor_alto': True},
        'Endividamento_Total_mean': {'peso': 0.10/1.15, 'melhor_alto': False},
        'Alavancagem_Financeira_mean': {'peso': 0.08/1.15, 'melhor_alto': False},
        'Liquidez_Corrente_mean': {'peso': 0.10/1.15, 'melhor_alto': True},
        'Receita_Liquida_slope_log': {'peso': 0.03/1.15, 'melhor_alto': True},
        'Lucro_Liquido_slope_log': {'peso': 0.05/1.15, 'melhor_alto': True},
        'Patrimonio_Liquido_slope_log': {'peso': 0.02/1.15, 'melhor_alto': True},
        'Divida_Liquida_slope_log': {'peso': 0.04/1.15, 'melhor_alto': False},
        'Caixa_Liquido_slope_log': {'peso': 0.03/1.15, 'melhor_alto': True},
        'Momentum_12m': {'peso': 0.15/1.15, 'melhor_alto': True},
    },
}

# Indicadores genéricos (fallback)
INDICADORES_SCORE = {
    'Margem_Liquida_mean': 0.15,
    'Margem_Operacional_mean': 0.20,
    'ROE_mean': 0.20,
    'ROA_mean': 0.20,
    'ROIC_mean': 0.20,
    'P/VP_mean': 0.10,
    'DY_mean': 0.30,
    'Endividamento_Total_mean': 0.15,
    'Alavancagem_Financeira_mean': 0.15,
    'Liquidez_Corrente_mean': 0.15,
    'Receita_Liquida_slope_log': 0.15,
    'Lucro_Liquido_slope_log': 0.20,
    'Patrimonio_Liquido_slope_log': 0.15,
    'Divida_Liquida_slope_log': 0.15,
    'Caixa_Liquido_slope_log': 0.15,
    'Momentum_12m': 0.15,
}
